#!/usr/bin/env python3

import argparse

def start():
    print("Lantern started")

def call(agent_name):
    print("Calling agent: ", agent_name)

def main():
    parser = argparse.ArgumentParser(prog="lantern", description="Lantern CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("start", help="Start server")
    call_parser = subparsers.add_parser("call", help="Call someone")
    call_parser.add_argument("agent_name", help="Name of the agent to call")
    args = parser.parse_args()

    if args.command == "start":
        start()
    elif args.command == "call":
        call(args.agent_name)
    else:
        print("Invalid command")

if __name__ == "__main__":
    main()
